### ISSUE TITLE
Materialeinsparung

### ISSUE THREAD

**Issue by balzer82** [MechLabEngineering/Low-Budget-Car-PC-Case#11]
Mal checken, ob nicht noch ein bisschen Material eingespart werden kann (vielleicht Dicke vom Deckel oder Boden), um günstiger für 3D Druck zu werden.

**Comment by RBorkert** [comment]
Es gibt nun zwei Versionen des Grundkörpers, V3.1 und V3.2. Sie unterscheiden sich nur in der Höhe der Box. Durch intensieve Umgestaltung und konsequenten Leichtbau konnte, im Vergleich zu Version V2, erheblich Material eingespart werden. Dies wirkt sich auch positiv auf die Kosten aus. V2 hatte einen Volumenbedarf von 211,71cm³. V3.1 benötigt 88,97cm³ (-58%), V3.2 99,52cm³ (-53%) Materialvolumen. Der Deckel passt bei beiden Versionen. Auch hier konnten weitere 17,5% Material gespart werden (56,62cm³ auf 46,7cm³). In der Mitte des Deckels ist jetzt die Orientierung der Achsen der IMU abgebieldet.

**Comment by balzer82** [comment]
Die Seitenwände an denen der Deckel fixiert ist, könnten wieder etwas dicker werden (Wabenhöhe).

**Comment by RBorkert** [comment]
Die Erhöhung der Steifigkeit der Seitenwände durch die Wabenhöhenvergrößerung ist im oberen Bereich der Seitenwände nicht Zielführend. Die maximale Höhe beläuft sich auf 1 bis 1,5 mm. Durch Stützleisten am Deckel wurde dennoch eine Erhöhung der Steifigkeit erreicht. Die Seitenwand stützt sich nun bei geschlossenem Deckel an diesem ab, ein extremes seitliches Eindrücken wird so unterbunden.
