### ISSUE TITLE
RasPi B+ Anpassungen

### ISSUE THREAD

**Issue by balzer82** [MechLabEngineering/Low-Budget-Car-PC-Case#12]
Dieser Tage kommt der neue [RaspiB+](http://www.raspberrypi.org/blog/#introducing-raspberry-pi-model-b-plus) heraus, welcher leider völlig anders aussieht.

Zum Glück gibt es genaue geometrische Specs:
![RaspbiB+](http://www.raspberrypi.org/wp-content/uploads/2014/07/mechanicalspecB+.png)

Außerdem:

* GPIO header has grown to 40 pins
* 4 USB 2.0 ports
* micro SD
* four squarely-placed mounting holes

**Comment by RBorkert** [comment]
Der Grundträger für den Raspberry Pi B+ wurde angepasst. Anschlussmöglichkeiten für micro USB (DC), USB, GPIO und Ethernet wurden berücksichtigt. Es gibt zwei Größenausführungen der Box.
