### ISSUE TITLE
Raspi Fixierung

### ISSUE THREAD

**Issue by balzer82** [MechLabEngineering/Low-Budget-Car-PC-Case#15]
Die Einpassung für den Raspi (samt Dorne für die Bohrungen) müsste etwas höher werden, damit der Raspi bei Erschütterung nicht locker wird.

**Comment by RBorkert** [comment]
Die Halterung für den Pi wurde noch einmal überarbeitet. Sie hat jetzt einen kleinen Einschub, wo der Pi reinkommt. Auf der anderen Seite wird der durch zwei Pins und einen Chlip gehalten.
